baseURL = "https://maquillajeasturias.netlify.com/"
#baseURL = "http://localhost:1313"
disqusShortname = ""
googleAnalytics = ""
languageCode = "es-es"
theme = "forty"
title = "Maquillaje Asturias"
publishDir = "public/"
[params]
banner_image = "peinado.jpg"
custom_css = []
custom_js = []
description = "Maquillaje profesional a domicilio en Asturias. Eventos y ocasiones especiales, no dudes en ponerte en contacto! "
favicon = "favicon.ico"
image = ""
name = "Cristina Rancaño Fernández"
[params.blog]
[params.error404]
heading = "Page couldn't be found"
text = "Please visit [this page](/)"
[params.contact]
formEmail = "info@maquillajeasturias.com"
[params.footer]
copyright = "HTML5 UP"
enable = true
[[params.footer.quicklinks]]
alt = "HTML5 UP"
text = "Design: "
url = "https://www.html5up.net"
[[params.footer.quicklinks]]
alt = "Ramiro Alvarez Fernández"
text = "Powered by:"
url = "https://ramiroalvfer.dev"
[params.tiles]
enable = true
[params.two]
buttonText = "Get Started"
enable = false
subtitle = "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero. \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt. Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus amet pharetra et feugiat tempus."
title = "Massa libero"
url = "blogs"
